version: 2.1

orbs:
  myorb:
    parameters:
      name:
        type: string
        default: 'world'
    executors:
      linux:
        docker:
          - image: circleci/android:api-29-node
    commands:
      run-test:
        parameters:
          api_level:
            type: integer
            default: 27
        steps:
          - run: echo << parameters.api_level >>
    jobs:
      run-tests:
        executor: linux
        steps:
          - run-test

workflows:
  main:
    jobs:
      - myorb/run-tests
