version: 2.1

jobs:
  check_changes_succeeds:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run: exit 0

  check_changes_fails:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run: exit 1

  needs_to_follow_check_changes_1:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run: exit 0

  needs_to_follow_check_changes_2:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run: exit 0

  runs_regardless_of_changes:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run: exit 0


workflows:
  test:
    jobs:
      - record_changes
      - check_for_changes:
          requires:
            - record_changes
      - downstream_job:
          requires:
            - check_for_changes
